### ISSUE TITLE
시, 도 로 나왔던 지도 강조에서 구, 군, 읍 까지 보여주는 기능 개발

### ISSUE THREAD

**Issue by miewone** [miewone/ingestJobPosting#30]

**Comment by miewone** [comment]
해당 기능 개발을 위해서는 svg 파일을 시,도 별로 구해야 했습니다.
@hamahipo 님, @SeungYunK 님 해당 파일로 각자 3개씩 작업해서 올려주시면 감사하겠습니다.
[maps.zip](https://github.com/miewone/ingestJobPosting/files/9937973/maps.zip)

**Comment by miewone** [comment]
![Ulsan](https://user-images.githubusercontent.com/51110811/199967808-6eda2fc1-53cc-42b3-8982-22b1619d85d7.svg)
![GeyongBuk](https://user-images.githubusercontent.com/51110811/199967813-7fd528ab-422d-4656-a4b1-3eb48108211a.svg)
![jejow](https://user-images.githubusercontent.com/51110811/199967817-e7e83065-4404-46ab-93bb-cb85f60dc725.svg)

**Comment by SeungYunK** [comment]
![gangwon](https://user-images.githubusercontent.com/91410947/200106594-15c18cd9-0acf-459f-b235-fdb15f5ac66d.svg)
![Gyungsangnam](https://user-images.githubusercontent.com/91410947/200106597-227d371d-7559-4539-bce1-1e85530c9325.svg)
![busan](https://user-images.githubusercontent.com/91410947/200106598-a942c820-f112-4ee0-b65f-5155dbe49d05.svg)

**Comment by hamahipo** [comment]
![Image](https://user-images.githubusercontent.com/86971120/200159537-e6b2e6b7-e974-432b-a9c3-3344eb8ffa8b.svg)

**Comment by hamahipo** [comment]
![Image](https://user-images.githubusercontent.com/86971120/200159542-b84da188-2fb3-4bd6-ae62-ee1673c89938.svg)

**Comment by hamahipo** [comment]
![Image](https://user-images.githubusercontent.com/86971120/200163707-4f322d52-f961-48b1-8857-dcaed7d9f536.svg)
